CREATE TABLE hap.tag (
tag_name VARCHAR(255) UNIQUE NOT NULL,
tag_desc VARCHAR(2000) NULL,
tag_id INT IDENTITY(10000,1) NOT NULL,
tag_created_date DATETIME DEFAULT GETDATE() NOT NULL,
PRIMARY KEY(tag_id)
);